Document: co-character-generator
Title: Debian co-character-generator Manual
Author: <insert document author here>
Abstract: This manual describes what co-character-generator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/co-character-generator/co-character-generator.sgml.gz

Format: postscript
Files: /usr/share/doc/co-character-generator/co-character-generator.ps.gz

Format: text
Files: /usr/share/doc/co-character-generator/co-character-generator.text.gz

Format: HTML
Index: /usr/share/doc/co-character-generator/html/index.html
Files: /usr/share/doc/co-character-generator/html/*.html
